resourcestring                                     {deutsch}

capClose='&Beenden';
hntClose='Programm beenden';
capConvert='STR &konvertieren';
hntConvert='Eine Untertiteldatei mit Telemetriedaten auswählen und in KML zum Ansehen in GoogleEarth konvertieren';
capSave='&Speichern';
hntSave='Flugbahn aus Telemetrie als KML speichern';
hntExtrude='Extrude zeichnet senkrechte Höhenlinien';
capMode='Ausgabeformat';
hntMode='Ausgabeformat wählen';
errSave='Willst du wirklich ohne zu speichern beenden?';

titOpen='Eine Untertiteldatei mit Telemetriedaten öffnen...';
titSave='Telemetriedaten als KML speichern...';
appName='SRT Telemetrie zu KML - Version ';
capDialog='Frage:';

