resourcestring                                     {deutsch}

capClose='&Beenden';
hntClose='Programm beenden';
capConvert='STR &konvertieren';
hntConvert='Eine Untertiteldatei mit Telemetriedaten auswählen und in KML zum Ansehen in GoogleEarth konvertieren';
capSave='&Speichern';
hntSave='Flugbahn aus Telemetrie als KML speichern';
errSave='Willst du wirklich ohne zu speichern beenden?';

titOpen='Eine Untertiteldatei mit Telemetriedaten öffnen...';
titSave='Telemetriedaten als KML speichern...';
appName='SRT Telemetrie zu KML - Version 0.1 (08/2023)';
capDialog='Frage:';

