resourcestring                                     {deutsch}

capClose='&Close';
hntClose='Close this application';
capConvert='STR con&vert';
hntConvert='Select a subtitle file with telemetry data and convert it to a KML file to use it on GoogleEarth';
capSave='&Save';
hntSave='Save flight track from telemetry data as KML file';
errSave='Do you really want to close without save?';

titOpen='Open subtitle file with telemetry data...';
titSave='Save telemetry as KML file...';
appName='SRT telemetry to KML - version 0.1 (08/2023)';
capDialog='Question:';

