resourcestring                                     {deutsch}

capClose='&Close';
hntClose='Close this application';
capConvert='STR con&vert';
hntConvert='Select a subtitle file with telemetry data and convert it to a KML file to use it on GoogleEarth';
capSave='&Save';
hntSave='Save flight track from telemetry data as KML file';
hntExtrude='Extend the linestring all the way to the ground';
capMode='Output format';
hntMode='Select output format';
errSave='Do you really want to close without save?';

titOpen='Open subtitle file with telemetry data...';
titSave='Save telemetry as KML file...';
appName='SRT telemetry to KML - version ';
capDialog='Question:';

